=== JDBC driver

Micronaut Data JDBC requires that an appropriate `java.sql.DataSource` bean is configured.

You can either do this manually or use the https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc[Micronaut JDBC] module which provides out-of-the-box support for configuring connection pooling with either Tomcat JDBC, Hikari, Commons DBCP or Oracle UCP.

=== SQL Logging

You can enable SQL logging by enabling trace logging for the `io.micronaut.data.query` logger. For example in `logback.xml`:

.Enabling SQL Query Logging
[source,xml]
----
<logger name="io.micronaut.data.query" level="trace" />
----

=== Creating the Schema

To create the database schema it is recommended you pair Micronaut Data with a SQL migration tool such as https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html[Flyway] or https://micronaut-projects.github.io/micronaut-liquibase/latest/guide/index.html[Liquibase].

SQL migration tools provide more complete support for creating and evolving your schema across a range of databases.

If you want to quickly test out Micronaut Data then you can set the `schema-generate` option of the data source to `create-drop` as well as the appropriate schema name:

NOTE: Most of the database migration tools use JDBC driver to make DB changes. If you use R2DBC you would need to separately configure JDBC data source.

.Using `schema-generate`
[configuration]
----
include::doc-examples/jdbc-example-java/src/main/resources/application.yml[]
----

The `schema-generate` option is currently only recommended for simple applications, testing and demos and is not considered production-ready. The dialect set in configuration is the dialect that will be used to generate the schema.

=== Setting the Dialect

As seen in the configuration above you should also configure the dialect. Although queries are precomputed in the repository some cases (like pagination) still require the dialect to specify. The following table summarizes the supported dialects:

.Supported JDBC / R2DBC Dialects
[cols=2*]
|===
|*Dialect*
|*Description*

|api:data.model.query.builder.sql.Dialect#H2[]
|The H2 database (typically used for in-memory testing)

|api:data.model.query.builder.sql.Dialect#MYSQL[]
|MySQL 5.5 or above

|api:data.model.query.builder.sql.Dialect#POSTGRES[]
|Postgres 9.5 or above

|api:data.model.query.builder.sql.Dialect#SQL_SERVER[]
|SQL Server 2012 or above

|api:data.model.query.builder.sql.Dialect#ORACLE[]
|Oracle 12c or above

|===

IMPORTANT: The dialect setting in configuration does *not* replace the need to ensure the correct dialect is set at the repository. If the dialect is H2 in configuration, the repository should have `@JdbcRepository(dialect = Dialect.H2)` / `@R2dbcRepository(dialect = Dialect.H2)`. Because repositories are computed at compile time, the configuration value is not known at that time.

=== Connection client info tracing

In order to trace SQL calls using `java.sql.Connection.setClientInfo(String, String)` method, you can
annotate a repository with the @api:data.connection.annotation.ConnectionClientInfo[] annotation. If the boolean member `enabled` is set to `false`, then Micronaut will not issue `setClientInfo` calls to the JDBC connection.
The annotation members `module` and `action` can set a custom module and action. If omitted, then the name of the module will default
to the class name (usually Micronaut Data repository class) annotated with the given annotation and action to the name of the method
being executed. In addition, the member `clientInfoAttributes` can be used to set arbitrary client info attributes to be set passed to the connection client info.

Note that the @api:data.connection.annotation.ConnectionClientInfo[] annotation can be used on either the class or the method, thus allowing customizaction of the  module or action individually.

For Oracle database, these values will be set to the JDBC connection using `setClientInfo("OCSID.MODULE", module)` and `setClientInfo("OCSID.ACTION", action)` respectively.
Additionally, if `${micronaut.application.name}` is set, then it will be used to call JDBC connection `setClientInfo("OCSID.CLIENTID", appName)`.
Please make sure that if you supply `OCSID.MODULE` or `OCSID.ACTION` in `ConnectionClientInfo` property `clientInfoAttributes` these values will be ignored because
`module` and `action` attributes are going to be mapped to  `OCSID.MODULE` and `OCSID.ACTION`.

Please note this is currently supported only for Oracle database connections. In order to enable Oracle connection client info to be set,
need to add this property `datasources.default.customize-oracle-client-info=true`.

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-data-jdbc-repository.html[Access a Database with Micronaut Data JDBC] to learn more.

